# this is the config of the blog, you can change the config here
# PLZ indicate the source when you want to modify it.


title: Edit _config.yaml to set your title
description: use the _config.yaml to change the format and the title for the blog
github_username: NeyMarKevin
